<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N60QB27" ignored="0" name="Test" tests="7" failures="2" timestamp="2022-12-16T16:32:40 IST" time="0.039" errors="0">
  <testcase name="doUserRegistration" time="0.001" classname="testcases.TestCase3"/>
  <testcase name="thirdTest" time="0.001" classname="testcases.TestCase3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TestCase3.thirdTest(TestCase3.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- thirdTest -->
  <testcase name="doLogin" time="0.0" classname="testcases.TestCase3">
    <skipped/>
  </testcase> <!-- doLogin -->
  <testcase name="forthTest" time="0.001" classname="testcases.TestCase3"/>
  <testcase name="doUserRegistration" time="0.001" classname="test2.TestCase1"/>
  <testcase name="doLogin" time="0.001" classname="test2.TestCase1"/>
  <testcase name="validateTitle" time="0.011" classname="test2.TestCase2">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true],
	expected [yahoo.com] but found [Gmail.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [yahoo.com] but found [Gmail.com]
at test2.TestCase2.validateTitle(TestCase2.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
</testsuite> <!-- Test -->
